### ISSUE TITLE
Error creating image when passing -k

### ISSUE THREAD

**Issue by lyricnz** [hamidnazari/amibaker#2]
When invoking amibaker with --keep-instance got an error while adding the permissions after the image was built. At the time, the machine was shutting down/making image/restarting. Perhaps this caused "create-image" to take longer>

Running aws --output json --profile mb-dev ec2 create-image --instance-id i-someinstance --name Dev/Prod Base Image 1437618735 --reboot
Running aws --output json --profile mb-dev ec2 modify-image-attribute --image-id ami-xxx --launch-permission {"Add": [{"UserId": "123"}, {"UserId": "456"}, {"UserId": "789"}, {"UserId": "234"}, {"UserId": "567"}, {"UserId": "999"}]}

A client error (InvalidAMIID.Unavailable) occurred when calling the ModifyImageAttribute operation: The AMI ID 'ami-xxx' is currently pending and may not be used for this operation

**Comment by hamidnazari** [comment]
Addressed by #3.
