### ISSUE TITLE
Error performing post-build SSH

### ISSUE THREAD

**Issue by lyricnz** [hamidnazari/amibaker#4]
When creating and destroying machines within a subnet, sooner or later the same IP address will be reused, resulting in an error like:

fabric.exceptions.NetworkError: Host key for 10.239.8.75 did not match pre-existing key! Server's key was changed recently, or possible man-in-the-middle attack.

Suggest provide option (or default) to avoid this check.

**Comment by hamidnazari** [comment]
Thanks for reporting this. Definitely a bug in the code. Will fix in the next release.
