### ISSUE TITLE
Allow timestamps to be string formatted

### ISSUE THREAD

**Issue by cgspeck** [hamidnazari/amibaker#9]
Jinja2 lacks the ability to nativey convert from unix time-stamp into human friendly specifiable string, e.g.

1438140192 -> 2015-07-29 03:23 

This could be done internally by replacing the timestamp with a datetime object which would allow  `{{ timestamp.strftime('%Y-%m-%d') }}`

http://stackoverflow.com/a/4830620/806799

**Comment by hamidnazari** [comment]
Addressed by #11.
